# Generated by Django 5.0.6 on 2024-06-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False)),
                ('tendanhmuc', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_danhmuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_danhmucs', to='app.danhmucsach')),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensach', models.CharField(max_length=200, null=True)),
                ('sochuong', models.FloatField()),
                ('ngaythem', models.DateTimeField(auto_now_add=True)),
                ('tacgia', models.CharField(max_length=200, null=True)),
                ('mota', models.CharField(max_length=200, null=True)),
                ('trangthai', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('danhmuc', models.ManyToManyField(related_name='danhmucs', to='app.danhmucsach')),
            ],
        ),
        migrations.CreateModel(
            name='ThichSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateTimeField(auto_now_add=True)),
                ('sachdathich', models.CharField(max_length=200, null=True)),
                ('sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sach')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaythich', models.DateTimeField(auto_now_add=True)),
                ('spsach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sach')),
                ('thich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thichsach')),
            ],
        ),
        migrations.CreateModel(
            name='ThongTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sach')),
                ('thich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thichsach')),
            ],
        ),
    ]
